//Deobfuscated By Mouath#2221 | ????#2221 D:\Game\private 2\False"!

package ca.hmod.sahr;

import java.util.*;

public class HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
{
    private static ArrayList<HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH> module;
    
    static {
        (HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module = new ArrayList<HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH>()).add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add(new HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add(new HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add(new HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHHHHHHHHHHHHHHHHHHHH());
        HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module.add((HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH)new HHHHHHHHH());
    }
    
    public ArrayList<HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH> getModules() {
        return HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.module;
    }
}
